sudo: false

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: gSo1Bzt64Wu+3Aeb8Plzn6D+nX17p3mglH9JbBhwn4Uq5IMBAbnhNkdJlZOPVLCnWdCD2EcEixwHCXt+Lh1K70IildzqfdCuSGRh/wu6v9J7ktf1shPthTi6K3TSilJ+kD2y26vapDlgBCAKpJ52j20nqJMC26g3rbxhWFygP8YZrdMvWs1mFJizS7A2Vo5+42D8pF2vSGCYjK+c0WgZc6IK4+QWkUsYQUYIEQ3bmnL779x4jQ0sOqeBNPYpVe3f38kQkca6sDA8DdWhWlBpLsxJe/7sUObxXk4/fk0OJivBJmAebaVf30pPuft7Jl/xJkRRqZ1T3Ws9D4T0qPNhgfA6ucD8zjTBSfzrKd77w9yi213HYa/NshXhAEb0S9Pwc30ZK3ejwU2hYlsA3uBAfSQBW7B1fSkNPKmvB+UxHiUMk+xdP6nuHjdZuom42mootI0bUssGKtMobz9j48hyXtFUIhPCLOC4GerNyOf/u15k+941nQWoelcFhTK412h9Zme9d+KPP5aSU8Hg1O1EUsHK8Gyn47U27Dg0TyfSvoZs7x9kC8if+CHvK6CEJ8Twp8oZb1/XtUFxbOXTa9raEvkw2V4LJt9hZihPEhdaSeMp9F1vbSx4i/pbwBzXS++J5d4txXRk/bAYUYwyFL4BqhCLMlYaQvErvI9s5hmiIbY=

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  
script: 
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output avr-g++ -mmcu=atmega88pa cpp/main.cpp -std=c++14 -Wall
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    
env:
  global:
    secure: gSo1Bzt64Wu+3Aeb8Plzn6D+nX17p3mglH9JbBhwn4Uq5IMBAbnhNkdJlZOPVLCnWdCD2EcEixwHCXt+Lh1K70IildzqfdCuSGRh/wu6v9J7ktf1shPthTi6K3TSilJ+kD2y26vapDlgBCAKpJ52j20nqJMC26g3rbxhWFygP8YZrdMvWs1mFJizS7A2Vo5+42D8pF2vSGCYjK+c0WgZc6IK4+QWkUsYQUYIEQ3bmnL779x4jQ0sOqeBNPYpVe3f38kQkca6sDA8DdWhWlBpLsxJe/7sUObxXk4/fk0OJivBJmAebaVf30pPuft7Jl/xJkRRqZ1T3Ws9D4T0qPNhgfA6ucD8zjTBSfzrKd77w9yi213HYa/NshXhAEb0S9Pwc30ZK3ejwU2hYlsA3uBAfSQBW7B1fSkNPKmvB+UxHiUMk+xdP6nuHjdZuom42mootI0bUssGKtMobz9j48hyXtFUIhPCLOC4GerNyOf/u15k+941nQWoelcFhTK412h9Zme9d+KPP5aSU8Hg1O1EUsHK8Gyn47U27Dg0TyfSvoZs7x9kC8if+CHvK6CEJ8Twp8oZb1/XtUFxbOXTa9raEvkw2V4LJt9hZihPEhdaSeMp9F1vbSx4i/pbwBzXS++J5d4txXRk/bAYUYwyFL4BqhCLMlYaQvErvI9s5hmiIbY=
