sudo: false

addons:
  sonarcloud:
    organization: "rigomate"
    token:
      secure: "FAIAOKmsoF8o+jBem+WMaR1BJArFoNVtWY2WP8TUoxRIN5pDtSTL6fpRKKjqyJioE4KjTJ52sk17Wufwf556vYjbTfXbz948DQRDdDTdeSJ5mc5vVg4dN4EVc1WVYbDRdQK1Euv7LX5FxsKkJYhv8vu9rE0RLymztGsoQ+ErKGxnkGUYe9sA/IgP3fCEllus6YidblXc+zlvcC023wtlLrakm3AsJQhRLYYhQG6F30Y5Nv2RvVAhi8VgrykNCK6+bxqCgZ9TVYDA89Y1zQLs4oWgNtRmZfMK32KwLsnLxzAIT1rTbTz02uEqrro4AFxIuY0eG3iv6K4qNFXVb4ginMu1LiYCfqMUIrIcJdRUq6OBf7JQJDrpMg+hb5CF2FLleUxqhNHZmpRJpUDEdVWhw7+rxUz+mao1LyrZqK6GFL6UJBaCMsDpP70J/1TxVcTvUbHPLCbwPmlNNZvvL61sp6FIugHd2xgSHuLhO3ZOnJfspPEsm8i/1zE03H0MnoUAgKLx2m0OYk9pa4o5k/l6VmVFR04+nWVbep8PKZo64JtUcbf1xoczSvyIfuKDjLQwhTr6WHUUvYhwEJ1MmJ1hPJ8WY8tP3+69bDTgimvoX99fw0gfZYHfcpFr9FNcY7xAnaF24vsWxktYKzcQY+jkrKOVwc87Z6QxwFsa41iJ0Tk="

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  
script: 
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output avr-g++ -mmcu=atmega88pa cpp/main.cpp -std=c++14 -Wall
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
