name: make-master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: |
          sudo apt-get install gcc-avr binutils-avr avr-libc
          avr-g++ -mmcu=atmega88pa cpp/main.cpp -std=c++14 -Wall